version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    environment:
      - REDIS_ARGS=--requirepass systempass
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=a12345678
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
